### ISSUE TITLE
Сообщить данные для получения сертификата финалиста

### ISSUE THREAD

**Issue by alehinsasha** [vadimitr/FinalTask#6]
В комментарии к этому issue напишите ваши:
- Имя Фамилию (в дательном падеже)
- Адрес электронной почты, на которую выслать сертификат

**Comment by vadimitr** [comment]
Митрофанову Вадиму Ремировичу, vadirm@yandex.ru

**Comment by alehinsasha** [comment]
Поздравительное письмо отправлено на указанный адрес! Прошу подтвердить получение.

**Comment by vadimitr** [comment]
Сертификат получил! Спасибо!
